# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ndrscodes/Dokumente/ba/temp/zenhammer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ndrscodes/Dokumente/ba/temp/zenhammer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndrscodes/Dokumente/ba/temp/zenhammer/CMakeFiles /home/ndrscodes/Dokumente/ba/temp/zenhammer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ndrscodes/Dokumente/ba/temp/zenhammer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bs

# Build rule for target.
bs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bs
.PHONY : bs

# fast build rule for target.
bs/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/build
.PHONY : bs/fast

#=============================================================================
# Target rules for targets named zenHammer

# Build rule for target.
zenHammer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zenHammer
.PHONY : zenHammer

# fast build rule for target.
zenHammer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zenHammer.dir/build.make CMakeFiles/zenHammer.dir/build
.PHONY : zenHammer/fast

#=============================================================================
# Target rules for targets named joinargs

# Build rule for target.
joinargs: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 joinargs
.PHONY : joinargs

# fast build rule for target.
joinargs/fast:
	$(MAKE) $(MAKESILENT) -f _deps/argagg-build/CMakeFiles/joinargs.dir/build.make _deps/argagg-build/CMakeFiles/joinargs.dir/build
.PHONY : joinargs/fast

#=============================================================================
# Target rules for targets named gengetopt_main1

# Build rule for target.
gengetopt_main1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gengetopt_main1
.PHONY : gengetopt_main1

# fast build rule for target.
gengetopt_main1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/argagg-build/CMakeFiles/gengetopt_main1.dir/build.make _deps/argagg-build/CMakeFiles/gengetopt_main1.dir/build
.PHONY : gengetopt_main1/fast

#=============================================================================
# Target rules for targets named argagg_test

# Build rule for target.
argagg_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 argagg_test
.PHONY : argagg_test

# fast build rule for target.
argagg_test/fast:
	$(MAKE) $(MAKESILENT) -f _deps/argagg-build/CMakeFiles/argagg_test.dir/build.make _deps/argagg-build/CMakeFiles/argagg_test.dir/build
.PHONY : argagg_test/fast

#=============================================================================
# Target rules for targets named asmjit

# Build rule for target.
asmjit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 asmjit
.PHONY : asmjit

# fast build rule for target.
asmjit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/asmjit-build/CMakeFiles/asmjit.dir/build.make _deps/asmjit-build/CMakeFiles/asmjit.dir/build
.PHONY : asmjit/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/Experimental.dir/build.make _deps/json-build/CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/Nightly.dir/build.make _deps/json-build/CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/Continuous.dir/build.make _deps/json-build/CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyMemoryCheck.dir/build.make _deps/json-build/CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyStart.dir/build.make _deps/json-build/CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyUpdate.dir/build.make _deps/json-build/CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyConfigure.dir/build.make _deps/json-build/CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyBuild.dir/build.make _deps/json-build/CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyTest.dir/build.make _deps/json-build/CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyCoverage.dir/build.make _deps/json-build/CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlyMemCheck.dir/build.make _deps/json-build/CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/NightlySubmit.dir/build.make _deps/json-build/CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalStart.dir/build.make _deps/json-build/CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalUpdate.dir/build.make _deps/json-build/CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalConfigure.dir/build.make _deps/json-build/CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalBuild.dir/build.make _deps/json-build/CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalTest.dir/build.make _deps/json-build/CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalCoverage.dir/build.make _deps/json-build/CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalMemCheck.dir/build.make _deps/json-build/CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ExperimentalSubmit.dir/build.make _deps/json-build/CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousStart.dir/build.make _deps/json-build/CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousUpdate.dir/build.make _deps/json-build/CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousConfigure.dir/build.make _deps/json-build/CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousBuild.dir/build.make _deps/json-build/CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousTest.dir/build.make _deps/json-build/CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousCoverage.dir/build.make _deps/json-build/CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousMemCheck.dir/build.make _deps/json-build/CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/CMakeFiles/ContinuousSubmit.dir/build.make _deps/json-build/CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named download_test_data

# Build rule for target.
download_test_data: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 download_test_data
.PHONY : download_test_data

# fast build rule for target.
download_test_data/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/download_test_data.dir/build.make _deps/json-build/test/CMakeFiles/download_test_data.dir/build
.PHONY : download_test_data/fast

#=============================================================================
# Target rules for targets named doctest_main

# Build rule for target.
doctest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 doctest_main
.PHONY : doctest_main

# fast build rule for target.
doctest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/doctest_main.dir/build.make _deps/json-build/test/CMakeFiles/doctest_main.dir/build
.PHONY : doctest_main/fast

#=============================================================================
# Target rules for targets named test-algorithms

# Build rule for target.
test-algorithms: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-algorithms
.PHONY : test-algorithms

# fast build rule for target.
test-algorithms/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-algorithms.dir/build.make _deps/json-build/test/CMakeFiles/test-algorithms.dir/build
.PHONY : test-algorithms/fast

#=============================================================================
# Target rules for targets named test-allocator

# Build rule for target.
test-allocator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-allocator
.PHONY : test-allocator

# fast build rule for target.
test-allocator/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-allocator.dir/build.make _deps/json-build/test/CMakeFiles/test-allocator.dir/build
.PHONY : test-allocator/fast

#=============================================================================
# Target rules for targets named test-alt-string

# Build rule for target.
test-alt-string: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-alt-string
.PHONY : test-alt-string

# fast build rule for target.
test-alt-string/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-alt-string.dir/build.make _deps/json-build/test/CMakeFiles/test-alt-string.dir/build
.PHONY : test-alt-string/fast

#=============================================================================
# Target rules for targets named test-assert_macro

# Build rule for target.
test-assert_macro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-assert_macro
.PHONY : test-assert_macro

# fast build rule for target.
test-assert_macro/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-assert_macro.dir/build.make _deps/json-build/test/CMakeFiles/test-assert_macro.dir/build
.PHONY : test-assert_macro/fast

#=============================================================================
# Target rules for targets named test-bson

# Build rule for target.
test-bson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-bson
.PHONY : test-bson

# fast build rule for target.
test-bson/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-bson.dir/build.make _deps/json-build/test/CMakeFiles/test-bson.dir/build
.PHONY : test-bson/fast

#=============================================================================
# Target rules for targets named test-capacity

# Build rule for target.
test-capacity: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-capacity
.PHONY : test-capacity

# fast build rule for target.
test-capacity/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-capacity.dir/build.make _deps/json-build/test/CMakeFiles/test-capacity.dir/build
.PHONY : test-capacity/fast

#=============================================================================
# Target rules for targets named test-cbor

# Build rule for target.
test-cbor: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-cbor
.PHONY : test-cbor

# fast build rule for target.
test-cbor/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-cbor.dir/build.make _deps/json-build/test/CMakeFiles/test-cbor.dir/build
.PHONY : test-cbor/fast

#=============================================================================
# Target rules for targets named test-class_const_iterator

# Build rule for target.
test-class_const_iterator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_const_iterator
.PHONY : test-class_const_iterator

# fast build rule for target.
test-class_const_iterator/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-class_const_iterator.dir/build.make _deps/json-build/test/CMakeFiles/test-class_const_iterator.dir/build
.PHONY : test-class_const_iterator/fast

#=============================================================================
# Target rules for targets named test-class_iterator

# Build rule for target.
test-class_iterator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_iterator
.PHONY : test-class_iterator

# fast build rule for target.
test-class_iterator/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-class_iterator.dir/build.make _deps/json-build/test/CMakeFiles/test-class_iterator.dir/build
.PHONY : test-class_iterator/fast

#=============================================================================
# Target rules for targets named test-class_lexer

# Build rule for target.
test-class_lexer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_lexer
.PHONY : test-class_lexer

# fast build rule for target.
test-class_lexer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-class_lexer.dir/build.make _deps/json-build/test/CMakeFiles/test-class_lexer.dir/build
.PHONY : test-class_lexer/fast

#=============================================================================
# Target rules for targets named test-class_parser

# Build rule for target.
test-class_parser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-class_parser
.PHONY : test-class_parser

# fast build rule for target.
test-class_parser/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-class_parser.dir/build.make _deps/json-build/test/CMakeFiles/test-class_parser.dir/build
.PHONY : test-class_parser/fast

#=============================================================================
# Target rules for targets named test-comparison

# Build rule for target.
test-comparison: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-comparison
.PHONY : test-comparison

# fast build rule for target.
test-comparison/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-comparison.dir/build.make _deps/json-build/test/CMakeFiles/test-comparison.dir/build
.PHONY : test-comparison/fast

#=============================================================================
# Target rules for targets named test-concepts

# Build rule for target.
test-concepts: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-concepts
.PHONY : test-concepts

# fast build rule for target.
test-concepts/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-concepts.dir/build.make _deps/json-build/test/CMakeFiles/test-concepts.dir/build
.PHONY : test-concepts/fast

#=============================================================================
# Target rules for targets named test-constructor1

# Build rule for target.
test-constructor1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-constructor1
.PHONY : test-constructor1

# fast build rule for target.
test-constructor1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-constructor1.dir/build.make _deps/json-build/test/CMakeFiles/test-constructor1.dir/build
.PHONY : test-constructor1/fast

#=============================================================================
# Target rules for targets named test-constructor2

# Build rule for target.
test-constructor2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-constructor2
.PHONY : test-constructor2

# fast build rule for target.
test-constructor2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-constructor2.dir/build.make _deps/json-build/test/CMakeFiles/test-constructor2.dir/build
.PHONY : test-constructor2/fast

#=============================================================================
# Target rules for targets named test-convenience

# Build rule for target.
test-convenience: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-convenience
.PHONY : test-convenience

# fast build rule for target.
test-convenience/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-convenience.dir/build.make _deps/json-build/test/CMakeFiles/test-convenience.dir/build
.PHONY : test-convenience/fast

#=============================================================================
# Target rules for targets named test-conversions

# Build rule for target.
test-conversions: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-conversions
.PHONY : test-conversions

# fast build rule for target.
test-conversions/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-conversions.dir/build.make _deps/json-build/test/CMakeFiles/test-conversions.dir/build
.PHONY : test-conversions/fast

#=============================================================================
# Target rules for targets named test-deserialization

# Build rule for target.
test-deserialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-deserialization
.PHONY : test-deserialization

# fast build rule for target.
test-deserialization/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-deserialization.dir/build.make _deps/json-build/test/CMakeFiles/test-deserialization.dir/build
.PHONY : test-deserialization/fast

#=============================================================================
# Target rules for targets named test-element_access1

# Build rule for target.
test-element_access1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-element_access1
.PHONY : test-element_access1

# fast build rule for target.
test-element_access1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-element_access1.dir/build.make _deps/json-build/test/CMakeFiles/test-element_access1.dir/build
.PHONY : test-element_access1/fast

#=============================================================================
# Target rules for targets named test-element_access2

# Build rule for target.
test-element_access2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-element_access2
.PHONY : test-element_access2

# fast build rule for target.
test-element_access2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-element_access2.dir/build.make _deps/json-build/test/CMakeFiles/test-element_access2.dir/build
.PHONY : test-element_access2/fast

#=============================================================================
# Target rules for targets named test-hash

# Build rule for target.
test-hash: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-hash
.PHONY : test-hash

# fast build rule for target.
test-hash/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-hash.dir/build.make _deps/json-build/test/CMakeFiles/test-hash.dir/build
.PHONY : test-hash/fast

#=============================================================================
# Target rules for targets named test-inspection

# Build rule for target.
test-inspection: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-inspection
.PHONY : test-inspection

# fast build rule for target.
test-inspection/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-inspection.dir/build.make _deps/json-build/test/CMakeFiles/test-inspection.dir/build
.PHONY : test-inspection/fast

#=============================================================================
# Target rules for targets named test-items

# Build rule for target.
test-items: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-items
.PHONY : test-items

# fast build rule for target.
test-items/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-items.dir/build.make _deps/json-build/test/CMakeFiles/test-items.dir/build
.PHONY : test-items/fast

#=============================================================================
# Target rules for targets named test-iterators1

# Build rule for target.
test-iterators1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-iterators1
.PHONY : test-iterators1

# fast build rule for target.
test-iterators1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-iterators1.dir/build.make _deps/json-build/test/CMakeFiles/test-iterators1.dir/build
.PHONY : test-iterators1/fast

#=============================================================================
# Target rules for targets named test-iterators2

# Build rule for target.
test-iterators2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-iterators2
.PHONY : test-iterators2

# fast build rule for target.
test-iterators2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-iterators2.dir/build.make _deps/json-build/test/CMakeFiles/test-iterators2.dir/build
.PHONY : test-iterators2/fast

#=============================================================================
# Target rules for targets named test-json_patch

# Build rule for target.
test-json_patch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-json_patch
.PHONY : test-json_patch

# fast build rule for target.
test-json_patch/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-json_patch.dir/build.make _deps/json-build/test/CMakeFiles/test-json_patch.dir/build
.PHONY : test-json_patch/fast

#=============================================================================
# Target rules for targets named test-json_pointer

# Build rule for target.
test-json_pointer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-json_pointer
.PHONY : test-json_pointer

# fast build rule for target.
test-json_pointer/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-json_pointer.dir/build.make _deps/json-build/test/CMakeFiles/test-json_pointer.dir/build
.PHONY : test-json_pointer/fast

#=============================================================================
# Target rules for targets named test-large_json

# Build rule for target.
test-large_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-large_json
.PHONY : test-large_json

# fast build rule for target.
test-large_json/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-large_json.dir/build.make _deps/json-build/test/CMakeFiles/test-large_json.dir/build
.PHONY : test-large_json/fast

#=============================================================================
# Target rules for targets named test-merge_patch

# Build rule for target.
test-merge_patch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-merge_patch
.PHONY : test-merge_patch

# fast build rule for target.
test-merge_patch/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-merge_patch.dir/build.make _deps/json-build/test/CMakeFiles/test-merge_patch.dir/build
.PHONY : test-merge_patch/fast

#=============================================================================
# Target rules for targets named test-meta

# Build rule for target.
test-meta: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-meta
.PHONY : test-meta

# fast build rule for target.
test-meta/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-meta.dir/build.make _deps/json-build/test/CMakeFiles/test-meta.dir/build
.PHONY : test-meta/fast

#=============================================================================
# Target rules for targets named test-modifiers

# Build rule for target.
test-modifiers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-modifiers
.PHONY : test-modifiers

# fast build rule for target.
test-modifiers/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-modifiers.dir/build.make _deps/json-build/test/CMakeFiles/test-modifiers.dir/build
.PHONY : test-modifiers/fast

#=============================================================================
# Target rules for targets named test-msgpack

# Build rule for target.
test-msgpack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-msgpack
.PHONY : test-msgpack

# fast build rule for target.
test-msgpack/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-msgpack.dir/build.make _deps/json-build/test/CMakeFiles/test-msgpack.dir/build
.PHONY : test-msgpack/fast

#=============================================================================
# Target rules for targets named test-noexcept

# Build rule for target.
test-noexcept: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-noexcept
.PHONY : test-noexcept

# fast build rule for target.
test-noexcept/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-noexcept.dir/build.make _deps/json-build/test/CMakeFiles/test-noexcept.dir/build
.PHONY : test-noexcept/fast

#=============================================================================
# Target rules for targets named test-ordered_json

# Build rule for target.
test-ordered_json: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ordered_json
.PHONY : test-ordered_json

# fast build rule for target.
test-ordered_json/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-ordered_json.dir/build.make _deps/json-build/test/CMakeFiles/test-ordered_json.dir/build
.PHONY : test-ordered_json/fast

#=============================================================================
# Target rules for targets named test-ordered_map

# Build rule for target.
test-ordered_map: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ordered_map
.PHONY : test-ordered_map

# fast build rule for target.
test-ordered_map/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-ordered_map.dir/build.make _deps/json-build/test/CMakeFiles/test-ordered_map.dir/build
.PHONY : test-ordered_map/fast

#=============================================================================
# Target rules for targets named test-pointer_access

# Build rule for target.
test-pointer_access: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-pointer_access
.PHONY : test-pointer_access

# fast build rule for target.
test-pointer_access/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-pointer_access.dir/build.make _deps/json-build/test/CMakeFiles/test-pointer_access.dir/build
.PHONY : test-pointer_access/fast

#=============================================================================
# Target rules for targets named test-readme

# Build rule for target.
test-readme: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-readme
.PHONY : test-readme

# fast build rule for target.
test-readme/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-readme.dir/build.make _deps/json-build/test/CMakeFiles/test-readme.dir/build
.PHONY : test-readme/fast

#=============================================================================
# Target rules for targets named test-reference_access

# Build rule for target.
test-reference_access: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-reference_access
.PHONY : test-reference_access

# fast build rule for target.
test-reference_access/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-reference_access.dir/build.make _deps/json-build/test/CMakeFiles/test-reference_access.dir/build
.PHONY : test-reference_access/fast

#=============================================================================
# Target rules for targets named test-regression1

# Build rule for target.
test-regression1: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression1
.PHONY : test-regression1

# fast build rule for target.
test-regression1/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-regression1.dir/build.make _deps/json-build/test/CMakeFiles/test-regression1.dir/build
.PHONY : test-regression1/fast

#=============================================================================
# Target rules for targets named test-regression2

# Build rule for target.
test-regression2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-regression2
.PHONY : test-regression2

# fast build rule for target.
test-regression2/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-regression2.dir/build.make _deps/json-build/test/CMakeFiles/test-regression2.dir/build
.PHONY : test-regression2/fast

#=============================================================================
# Target rules for targets named test-serialization

# Build rule for target.
test-serialization: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-serialization
.PHONY : test-serialization

# fast build rule for target.
test-serialization/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-serialization.dir/build.make _deps/json-build/test/CMakeFiles/test-serialization.dir/build
.PHONY : test-serialization/fast

#=============================================================================
# Target rules for targets named test-testsuites

# Build rule for target.
test-testsuites: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-testsuites
.PHONY : test-testsuites

# fast build rule for target.
test-testsuites/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-testsuites.dir/build.make _deps/json-build/test/CMakeFiles/test-testsuites.dir/build
.PHONY : test-testsuites/fast

#=============================================================================
# Target rules for targets named test-to_chars

# Build rule for target.
test-to_chars: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-to_chars
.PHONY : test-to_chars

# fast build rule for target.
test-to_chars/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-to_chars.dir/build.make _deps/json-build/test/CMakeFiles/test-to_chars.dir/build
.PHONY : test-to_chars/fast

#=============================================================================
# Target rules for targets named test-ubjson

# Build rule for target.
test-ubjson: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-ubjson
.PHONY : test-ubjson

# fast build rule for target.
test-ubjson/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-ubjson.dir/build.make _deps/json-build/test/CMakeFiles/test-ubjson.dir/build
.PHONY : test-ubjson/fast

#=============================================================================
# Target rules for targets named test-udt

# Build rule for target.
test-udt: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-udt
.PHONY : test-udt

# fast build rule for target.
test-udt/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-udt.dir/build.make _deps/json-build/test/CMakeFiles/test-udt.dir/build
.PHONY : test-udt/fast

#=============================================================================
# Target rules for targets named test-udt_macro

# Build rule for target.
test-udt_macro: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-udt_macro
.PHONY : test-udt_macro

# fast build rule for target.
test-udt_macro/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-udt_macro.dir/build.make _deps/json-build/test/CMakeFiles/test-udt_macro.dir/build
.PHONY : test-udt_macro/fast

#=============================================================================
# Target rules for targets named test-unicode

# Build rule for target.
test-unicode: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-unicode
.PHONY : test-unicode

# fast build rule for target.
test-unicode/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-unicode.dir/build.make _deps/json-build/test/CMakeFiles/test-unicode.dir/build
.PHONY : test-unicode/fast

#=============================================================================
# Target rules for targets named test-user_defined_input

# Build rule for target.
test-user_defined_input: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-user_defined_input
.PHONY : test-user_defined_input

# fast build rule for target.
test-user_defined_input/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-user_defined_input.dir/build.make _deps/json-build/test/CMakeFiles/test-user_defined_input.dir/build
.PHONY : test-user_defined_input/fast

#=============================================================================
# Target rules for targets named test-wstring

# Build rule for target.
test-wstring: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test-wstring
.PHONY : test-wstring

# fast build rule for target.
test-wstring/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/test-wstring.dir/build.make _deps/json-build/test/CMakeFiles/test-wstring.dir/build
.PHONY : test-wstring/fast

#=============================================================================
# Target rules for targets named json_unit

# Build rule for target.
json_unit: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 json_unit
.PHONY : json_unit

# fast build rule for target.
json_unit/fast:
	$(MAKE) $(MAKESILENT) -f _deps/json-build/test/CMakeFiles/json_unit.dir/build.make _deps/json-build/test/CMakeFiles/json_unit.dir/build
.PHONY : json_unit/fast

src/Forges/FuzzyHammerer.o: src/Forges/FuzzyHammerer.cpp.o
.PHONY : src/Forges/FuzzyHammerer.o

# target to build an object file
src/Forges/FuzzyHammerer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/FuzzyHammerer.cpp.o
.PHONY : src/Forges/FuzzyHammerer.cpp.o

src/Forges/FuzzyHammerer.i: src/Forges/FuzzyHammerer.cpp.i
.PHONY : src/Forges/FuzzyHammerer.i

# target to preprocess a source file
src/Forges/FuzzyHammerer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/FuzzyHammerer.cpp.i
.PHONY : src/Forges/FuzzyHammerer.cpp.i

src/Forges/FuzzyHammerer.s: src/Forges/FuzzyHammerer.cpp.s
.PHONY : src/Forges/FuzzyHammerer.s

# target to generate assembly for a file
src/Forges/FuzzyHammerer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/FuzzyHammerer.cpp.s
.PHONY : src/Forges/FuzzyHammerer.cpp.s

src/Forges/ReplayingHammerer.o: src/Forges/ReplayingHammerer.cpp.o
.PHONY : src/Forges/ReplayingHammerer.o

# target to build an object file
src/Forges/ReplayingHammerer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/ReplayingHammerer.cpp.o
.PHONY : src/Forges/ReplayingHammerer.cpp.o

src/Forges/ReplayingHammerer.i: src/Forges/ReplayingHammerer.cpp.i
.PHONY : src/Forges/ReplayingHammerer.i

# target to preprocess a source file
src/Forges/ReplayingHammerer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/ReplayingHammerer.cpp.i
.PHONY : src/Forges/ReplayingHammerer.cpp.i

src/Forges/ReplayingHammerer.s: src/Forges/ReplayingHammerer.cpp.s
.PHONY : src/Forges/ReplayingHammerer.s

# target to generate assembly for a file
src/Forges/ReplayingHammerer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Forges/ReplayingHammerer.cpp.s
.PHONY : src/Forges/ReplayingHammerer.cpp.s

src/Fuzzer/Aggressor.o: src/Fuzzer/Aggressor.cpp.o
.PHONY : src/Fuzzer/Aggressor.o

# target to build an object file
src/Fuzzer/Aggressor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/Aggressor.cpp.o
.PHONY : src/Fuzzer/Aggressor.cpp.o

src/Fuzzer/Aggressor.i: src/Fuzzer/Aggressor.cpp.i
.PHONY : src/Fuzzer/Aggressor.i

# target to preprocess a source file
src/Fuzzer/Aggressor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/Aggressor.cpp.i
.PHONY : src/Fuzzer/Aggressor.cpp.i

src/Fuzzer/Aggressor.s: src/Fuzzer/Aggressor.cpp.s
.PHONY : src/Fuzzer/Aggressor.s

# target to generate assembly for a file
src/Fuzzer/Aggressor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/Aggressor.cpp.s
.PHONY : src/Fuzzer/Aggressor.cpp.s

src/Fuzzer/AggressorAccessPattern.o: src/Fuzzer/AggressorAccessPattern.cpp.o
.PHONY : src/Fuzzer/AggressorAccessPattern.o

# target to build an object file
src/Fuzzer/AggressorAccessPattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/AggressorAccessPattern.cpp.o
.PHONY : src/Fuzzer/AggressorAccessPattern.cpp.o

src/Fuzzer/AggressorAccessPattern.i: src/Fuzzer/AggressorAccessPattern.cpp.i
.PHONY : src/Fuzzer/AggressorAccessPattern.i

# target to preprocess a source file
src/Fuzzer/AggressorAccessPattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/AggressorAccessPattern.cpp.i
.PHONY : src/Fuzzer/AggressorAccessPattern.cpp.i

src/Fuzzer/AggressorAccessPattern.s: src/Fuzzer/AggressorAccessPattern.cpp.s
.PHONY : src/Fuzzer/AggressorAccessPattern.s

# target to generate assembly for a file
src/Fuzzer/AggressorAccessPattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/AggressorAccessPattern.cpp.s
.PHONY : src/Fuzzer/AggressorAccessPattern.cpp.s

src/Fuzzer/BitFlip.o: src/Fuzzer/BitFlip.cpp.o
.PHONY : src/Fuzzer/BitFlip.o

# target to build an object file
src/Fuzzer/BitFlip.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/BitFlip.cpp.o
.PHONY : src/Fuzzer/BitFlip.cpp.o

src/Fuzzer/BitFlip.i: src/Fuzzer/BitFlip.cpp.i
.PHONY : src/Fuzzer/BitFlip.i

# target to preprocess a source file
src/Fuzzer/BitFlip.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/BitFlip.cpp.i
.PHONY : src/Fuzzer/BitFlip.cpp.i

src/Fuzzer/BitFlip.s: src/Fuzzer/BitFlip.cpp.s
.PHONY : src/Fuzzer/BitFlip.s

# target to generate assembly for a file
src/Fuzzer/BitFlip.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/BitFlip.cpp.s
.PHONY : src/Fuzzer/BitFlip.cpp.s

src/Fuzzer/CodeJitter.o: src/Fuzzer/CodeJitter.cpp.o
.PHONY : src/Fuzzer/CodeJitter.o

# target to build an object file
src/Fuzzer/CodeJitter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/CodeJitter.cpp.o
.PHONY : src/Fuzzer/CodeJitter.cpp.o

src/Fuzzer/CodeJitter.i: src/Fuzzer/CodeJitter.cpp.i
.PHONY : src/Fuzzer/CodeJitter.i

# target to preprocess a source file
src/Fuzzer/CodeJitter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/CodeJitter.cpp.i
.PHONY : src/Fuzzer/CodeJitter.cpp.i

src/Fuzzer/CodeJitter.s: src/Fuzzer/CodeJitter.cpp.s
.PHONY : src/Fuzzer/CodeJitter.s

# target to generate assembly for a file
src/Fuzzer/CodeJitter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/CodeJitter.cpp.s
.PHONY : src/Fuzzer/CodeJitter.cpp.s

src/Fuzzer/FuzzingParameterSet.o: src/Fuzzer/FuzzingParameterSet.cpp.o
.PHONY : src/Fuzzer/FuzzingParameterSet.o

# target to build an object file
src/Fuzzer/FuzzingParameterSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/FuzzingParameterSet.cpp.o
.PHONY : src/Fuzzer/FuzzingParameterSet.cpp.o

src/Fuzzer/FuzzingParameterSet.i: src/Fuzzer/FuzzingParameterSet.cpp.i
.PHONY : src/Fuzzer/FuzzingParameterSet.i

# target to preprocess a source file
src/Fuzzer/FuzzingParameterSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/FuzzingParameterSet.cpp.i
.PHONY : src/Fuzzer/FuzzingParameterSet.cpp.i

src/Fuzzer/FuzzingParameterSet.s: src/Fuzzer/FuzzingParameterSet.cpp.s
.PHONY : src/Fuzzer/FuzzingParameterSet.s

# target to generate assembly for a file
src/Fuzzer/FuzzingParameterSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/FuzzingParameterSet.cpp.s
.PHONY : src/Fuzzer/FuzzingParameterSet.cpp.s

src/Fuzzer/HammeringPattern.o: src/Fuzzer/HammeringPattern.cpp.o
.PHONY : src/Fuzzer/HammeringPattern.o

# target to build an object file
src/Fuzzer/HammeringPattern.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/HammeringPattern.cpp.o
.PHONY : src/Fuzzer/HammeringPattern.cpp.o

src/Fuzzer/HammeringPattern.i: src/Fuzzer/HammeringPattern.cpp.i
.PHONY : src/Fuzzer/HammeringPattern.i

# target to preprocess a source file
src/Fuzzer/HammeringPattern.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/HammeringPattern.cpp.i
.PHONY : src/Fuzzer/HammeringPattern.cpp.i

src/Fuzzer/HammeringPattern.s: src/Fuzzer/HammeringPattern.cpp.s
.PHONY : src/Fuzzer/HammeringPattern.s

# target to generate assembly for a file
src/Fuzzer/HammeringPattern.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/HammeringPattern.cpp.s
.PHONY : src/Fuzzer/HammeringPattern.cpp.s

src/Fuzzer/PatternAddressMapper.o: src/Fuzzer/PatternAddressMapper.cpp.o
.PHONY : src/Fuzzer/PatternAddressMapper.o

# target to build an object file
src/Fuzzer/PatternAddressMapper.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternAddressMapper.cpp.o
.PHONY : src/Fuzzer/PatternAddressMapper.cpp.o

src/Fuzzer/PatternAddressMapper.i: src/Fuzzer/PatternAddressMapper.cpp.i
.PHONY : src/Fuzzer/PatternAddressMapper.i

# target to preprocess a source file
src/Fuzzer/PatternAddressMapper.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternAddressMapper.cpp.i
.PHONY : src/Fuzzer/PatternAddressMapper.cpp.i

src/Fuzzer/PatternAddressMapper.s: src/Fuzzer/PatternAddressMapper.cpp.s
.PHONY : src/Fuzzer/PatternAddressMapper.s

# target to generate assembly for a file
src/Fuzzer/PatternAddressMapper.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternAddressMapper.cpp.s
.PHONY : src/Fuzzer/PatternAddressMapper.cpp.s

src/Fuzzer/PatternBuilder.o: src/Fuzzer/PatternBuilder.cpp.o
.PHONY : src/Fuzzer/PatternBuilder.o

# target to build an object file
src/Fuzzer/PatternBuilder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternBuilder.cpp.o
.PHONY : src/Fuzzer/PatternBuilder.cpp.o

src/Fuzzer/PatternBuilder.i: src/Fuzzer/PatternBuilder.cpp.i
.PHONY : src/Fuzzer/PatternBuilder.i

# target to preprocess a source file
src/Fuzzer/PatternBuilder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternBuilder.cpp.i
.PHONY : src/Fuzzer/PatternBuilder.cpp.i

src/Fuzzer/PatternBuilder.s: src/Fuzzer/PatternBuilder.cpp.s
.PHONY : src/Fuzzer/PatternBuilder.s

# target to generate assembly for a file
src/Fuzzer/PatternBuilder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Fuzzer/PatternBuilder.cpp.s
.PHONY : src/Fuzzer/PatternBuilder.cpp.s

src/Memory/DRAMAddr.o: src/Memory/DRAMAddr.cpp.o
.PHONY : src/Memory/DRAMAddr.o

# target to build an object file
src/Memory/DRAMAddr.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMAddr.cpp.o
.PHONY : src/Memory/DRAMAddr.cpp.o

src/Memory/DRAMAddr.i: src/Memory/DRAMAddr.cpp.i
.PHONY : src/Memory/DRAMAddr.i

# target to preprocess a source file
src/Memory/DRAMAddr.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMAddr.cpp.i
.PHONY : src/Memory/DRAMAddr.cpp.i

src/Memory/DRAMAddr.s: src/Memory/DRAMAddr.cpp.s
.PHONY : src/Memory/DRAMAddr.s

# target to generate assembly for a file
src/Memory/DRAMAddr.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMAddr.cpp.s
.PHONY : src/Memory/DRAMAddr.cpp.s

src/Memory/DRAMConfig.o: src/Memory/DRAMConfig.cpp.o
.PHONY : src/Memory/DRAMConfig.o

# target to build an object file
src/Memory/DRAMConfig.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMConfig.cpp.o
.PHONY : src/Memory/DRAMConfig.cpp.o

src/Memory/DRAMConfig.i: src/Memory/DRAMConfig.cpp.i
.PHONY : src/Memory/DRAMConfig.i

# target to preprocess a source file
src/Memory/DRAMConfig.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMConfig.cpp.i
.PHONY : src/Memory/DRAMConfig.cpp.i

src/Memory/DRAMConfig.s: src/Memory/DRAMConfig.cpp.s
.PHONY : src/Memory/DRAMConfig.s

# target to generate assembly for a file
src/Memory/DRAMConfig.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DRAMConfig.cpp.s
.PHONY : src/Memory/DRAMConfig.cpp.s

src/Memory/DramAnalyzer.o: src/Memory/DramAnalyzer.cpp.o
.PHONY : src/Memory/DramAnalyzer.o

# target to build an object file
src/Memory/DramAnalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DramAnalyzer.cpp.o
.PHONY : src/Memory/DramAnalyzer.cpp.o

src/Memory/DramAnalyzer.i: src/Memory/DramAnalyzer.cpp.i
.PHONY : src/Memory/DramAnalyzer.i

# target to preprocess a source file
src/Memory/DramAnalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DramAnalyzer.cpp.i
.PHONY : src/Memory/DramAnalyzer.cpp.i

src/Memory/DramAnalyzer.s: src/Memory/DramAnalyzer.cpp.s
.PHONY : src/Memory/DramAnalyzer.s

# target to generate assembly for a file
src/Memory/DramAnalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/DramAnalyzer.cpp.s
.PHONY : src/Memory/DramAnalyzer.cpp.s

src/Memory/Memory.o: src/Memory/Memory.cpp.o
.PHONY : src/Memory/Memory.o

# target to build an object file
src/Memory/Memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/Memory.cpp.o
.PHONY : src/Memory/Memory.cpp.o

src/Memory/Memory.i: src/Memory/Memory.cpp.i
.PHONY : src/Memory/Memory.i

# target to preprocess a source file
src/Memory/Memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/Memory.cpp.i
.PHONY : src/Memory/Memory.cpp.i

src/Memory/Memory.s: src/Memory/Memory.cpp.s
.PHONY : src/Memory/Memory.s

# target to generate assembly for a file
src/Memory/Memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Memory/Memory.cpp.s
.PHONY : src/Memory/Memory.cpp.s

src/Utilities/Enums.o: src/Utilities/Enums.cpp.o
.PHONY : src/Utilities/Enums.o

# target to build an object file
src/Utilities/Enums.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Enums.cpp.o
.PHONY : src/Utilities/Enums.cpp.o

src/Utilities/Enums.i: src/Utilities/Enums.cpp.i
.PHONY : src/Utilities/Enums.i

# target to preprocess a source file
src/Utilities/Enums.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Enums.cpp.i
.PHONY : src/Utilities/Enums.cpp.i

src/Utilities/Enums.s: src/Utilities/Enums.cpp.s
.PHONY : src/Utilities/Enums.s

# target to generate assembly for a file
src/Utilities/Enums.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Enums.cpp.s
.PHONY : src/Utilities/Enums.cpp.s

src/Utilities/Logger.o: src/Utilities/Logger.cpp.o
.PHONY : src/Utilities/Logger.o

# target to build an object file
src/Utilities/Logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Logger.cpp.o
.PHONY : src/Utilities/Logger.cpp.o

src/Utilities/Logger.i: src/Utilities/Logger.cpp.i
.PHONY : src/Utilities/Logger.i

# target to preprocess a source file
src/Utilities/Logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Logger.cpp.i
.PHONY : src/Utilities/Logger.cpp.i

src/Utilities/Logger.s: src/Utilities/Logger.cpp.s
.PHONY : src/Utilities/Logger.s

# target to generate assembly for a file
src/Utilities/Logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bs.dir/build.make CMakeFiles/bs.dir/src/Utilities/Logger.cpp.s
.PHONY : src/Utilities/Logger.cpp.s

src/ZenHammer.o: src/ZenHammer.cpp.o
.PHONY : src/ZenHammer.o

# target to build an object file
src/ZenHammer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zenHammer.dir/build.make CMakeFiles/zenHammer.dir/src/ZenHammer.cpp.o
.PHONY : src/ZenHammer.cpp.o

src/ZenHammer.i: src/ZenHammer.cpp.i
.PHONY : src/ZenHammer.i

# target to preprocess a source file
src/ZenHammer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zenHammer.dir/build.make CMakeFiles/zenHammer.dir/src/ZenHammer.cpp.i
.PHONY : src/ZenHammer.cpp.i

src/ZenHammer.s: src/ZenHammer.cpp.s
.PHONY : src/ZenHammer.s

# target to generate assembly for a file
src/ZenHammer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zenHammer.dir/build.make CMakeFiles/zenHammer.dir/src/ZenHammer.cpp.s
.PHONY : src/ZenHammer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Continuous"
	@echo "... ContinuousBuild"
	@echo "... ContinuousConfigure"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousMemCheck"
	@echo "... ContinuousStart"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousTest"
	@echo "... ContinuousUpdate"
	@echo "... Experimental"
	@echo "... ExperimentalBuild"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ExperimentalSubmit"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalUpdate"
	@echo "... Nightly"
	@echo "... NightlyBuild"
	@echo "... NightlyConfigure"
	@echo "... NightlyCoverage"
	@echo "... NightlyMemCheck"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyStart"
	@echo "... NightlySubmit"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... download_test_data"
	@echo "... argagg_test"
	@echo "... asmjit"
	@echo "... bs"
	@echo "... doctest_main"
	@echo "... gengetopt_main1"
	@echo "... joinargs"
	@echo "... json_unit"
	@echo "... test-algorithms"
	@echo "... test-allocator"
	@echo "... test-alt-string"
	@echo "... test-assert_macro"
	@echo "... test-bson"
	@echo "... test-capacity"
	@echo "... test-cbor"
	@echo "... test-class_const_iterator"
	@echo "... test-class_iterator"
	@echo "... test-class_lexer"
	@echo "... test-class_parser"
	@echo "... test-comparison"
	@echo "... test-concepts"
	@echo "... test-constructor1"
	@echo "... test-constructor2"
	@echo "... test-convenience"
	@echo "... test-conversions"
	@echo "... test-deserialization"
	@echo "... test-element_access1"
	@echo "... test-element_access2"
	@echo "... test-hash"
	@echo "... test-inspection"
	@echo "... test-items"
	@echo "... test-iterators1"
	@echo "... test-iterators2"
	@echo "... test-json_patch"
	@echo "... test-json_pointer"
	@echo "... test-large_json"
	@echo "... test-merge_patch"
	@echo "... test-meta"
	@echo "... test-modifiers"
	@echo "... test-msgpack"
	@echo "... test-noexcept"
	@echo "... test-ordered_json"
	@echo "... test-ordered_map"
	@echo "... test-pointer_access"
	@echo "... test-readme"
	@echo "... test-reference_access"
	@echo "... test-regression1"
	@echo "... test-regression2"
	@echo "... test-serialization"
	@echo "... test-testsuites"
	@echo "... test-to_chars"
	@echo "... test-ubjson"
	@echo "... test-udt"
	@echo "... test-udt_macro"
	@echo "... test-unicode"
	@echo "... test-user_defined_input"
	@echo "... test-wstring"
	@echo "... zenHammer"
	@echo "... src/Forges/FuzzyHammerer.o"
	@echo "... src/Forges/FuzzyHammerer.i"
	@echo "... src/Forges/FuzzyHammerer.s"
	@echo "... src/Forges/ReplayingHammerer.o"
	@echo "... src/Forges/ReplayingHammerer.i"
	@echo "... src/Forges/ReplayingHammerer.s"
	@echo "... src/Fuzzer/Aggressor.o"
	@echo "... src/Fuzzer/Aggressor.i"
	@echo "... src/Fuzzer/Aggressor.s"
	@echo "... src/Fuzzer/AggressorAccessPattern.o"
	@echo "... src/Fuzzer/AggressorAccessPattern.i"
	@echo "... src/Fuzzer/AggressorAccessPattern.s"
	@echo "... src/Fuzzer/BitFlip.o"
	@echo "... src/Fuzzer/BitFlip.i"
	@echo "... src/Fuzzer/BitFlip.s"
	@echo "... src/Fuzzer/CodeJitter.o"
	@echo "... src/Fuzzer/CodeJitter.i"
	@echo "... src/Fuzzer/CodeJitter.s"
	@echo "... src/Fuzzer/FuzzingParameterSet.o"
	@echo "... src/Fuzzer/FuzzingParameterSet.i"
	@echo "... src/Fuzzer/FuzzingParameterSet.s"
	@echo "... src/Fuzzer/HammeringPattern.o"
	@echo "... src/Fuzzer/HammeringPattern.i"
	@echo "... src/Fuzzer/HammeringPattern.s"
	@echo "... src/Fuzzer/PatternAddressMapper.o"
	@echo "... src/Fuzzer/PatternAddressMapper.i"
	@echo "... src/Fuzzer/PatternAddressMapper.s"
	@echo "... src/Fuzzer/PatternBuilder.o"
	@echo "... src/Fuzzer/PatternBuilder.i"
	@echo "... src/Fuzzer/PatternBuilder.s"
	@echo "... src/Memory/DRAMAddr.o"
	@echo "... src/Memory/DRAMAddr.i"
	@echo "... src/Memory/DRAMAddr.s"
	@echo "... src/Memory/DRAMConfig.o"
	@echo "... src/Memory/DRAMConfig.i"
	@echo "... src/Memory/DRAMConfig.s"
	@echo "... src/Memory/DramAnalyzer.o"
	@echo "... src/Memory/DramAnalyzer.i"
	@echo "... src/Memory/DramAnalyzer.s"
	@echo "... src/Memory/Memory.o"
	@echo "... src/Memory/Memory.i"
	@echo "... src/Memory/Memory.s"
	@echo "... src/Utilities/Enums.o"
	@echo "... src/Utilities/Enums.i"
	@echo "... src/Utilities/Enums.s"
	@echo "... src/Utilities/Logger.o"
	@echo "... src/Utilities/Logger.i"
	@echo "... src/Utilities/Logger.s"
	@echo "... src/ZenHammer.o"
	@echo "... src/ZenHammer.i"
	@echo "... src/ZenHammer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

